name: CI
 
on:
  push:
    branches: ["*"]

 
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      env:
       TURBO_TEAM: k6
       TURBO_TOKEN: orXUG7C0upy1PfeztANQZEBp
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 7.25.0
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
 
        - name: Install dependencies
          run: pnpm install --no-frozen-lockfile
 
        - name: Build
          run: pnpm build
 
        - name: Test
          run: pnpm test